services:
  db:
    image: postgres           
    container_name: driftPSQL   
    restart: always
    environment:
      POSTGRES_USER: drift
      POSTGRES_PASSWORD: drift
      POSTGRES_DB: drift
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: