-- +goose Up
-- User domain schema
CREATE TYPE user_status AS ENUM ('active', 'pending');

CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    stytch_user_id TEXT NOT NULL UNIQUE,
    first_name TEXT,
    last_name TEXT,
    email TEXT NOT NULL,
    status user_status NOT NULL DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_users_stytch_user_id ON users(stytch_user_id);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- Link domain schema
CREATE TABLE IF NOT EXISTS link_item (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    access_token TEXT NOT NULL, -- encrypt at rest
    item_id TEXT NOT NULL,
    institution_id TEXT,
    institution_name TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_link_item_user_id ON link_item(user_id);
CREATE INDEX IF NOT EXISTS idx_link_item_item_id ON link_item(item_id);
CREATE INDEX IF NOT EXISTS idx_link_item_access_token ON link_item(access_token);

CREATE TABLE IF NOT EXISTS link_account (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    plaid_account_id TEXT NOT NULL UNIQUE, -- encrypt at rest
    item_id BIGINT NOT NULL REFERENCES link_item(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT,
    official_name TEXT,
    mask TEXT,
    subtype TEXT,
    type TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_link_account_plaid_account_id ON link_account(plaid_account_id);
CREATE INDEX IF NOT EXISTS idx_link_account_item_id ON link_account(item_id);
CREATE INDEX IF NOT EXISTS idx_link_account_user_id ON link_account(user_id);

-- +goose Down
DROP INDEX IF EXISTS idx_link_account_user_id;
DROP INDEX IF EXISTS idx_link_account_item_id;
DROP INDEX IF EXISTS idx_link_account_plaid_account_id;
DROP TABLE IF EXISTS link_account;

DROP INDEX IF EXISTS idx_link_item_access_token;
DROP INDEX IF EXISTS idx_link_item_item_id;
DROP INDEX IF EXISTS idx_link_item_user_id;
DROP TABLE IF EXISTS link_item;

DROP INDEX IF EXISTS idx_users_email;
DROP INDEX IF EXISTS idx_users_stytch_user_id;
DROP TABLE IF EXISTS users;
DROP TYPE IF EXISTS user_status; 