-- +goose Up
CREATE TABLE IF NOT EXISTS link_item (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    access_token TEXT NOT NULL, -- encrypt at rest
    item_id TEXT NOT NULL,
    institution_id TEXT,
    institution_name TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_link_item_user_id ON link_item(user_id);
CREATE INDEX IF NOT EXISTS idx_link_item_item_id ON link_item(item_id);
CREATE INDEX IF NOT EXISTS idx_link_item_access_token ON link_item(access_token); 

-- +goose Down
DROP INDEX IF EXISTS idx_link_item_user_id;
DROP INDEX IF EXISTS idx_link_item_item_id;
DROP INDEX IF EXISTS idx_link_item_access_token;
DROP TABLE IF EXISTS link_item; 