-- +goose Up
CREATE TABLE IF NOT EXISTS link_account (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    plaid_account_id TEXT NOT NULL UNIQUE, -- encrypt at rest
    item_id BIGINT NOT NULL REFERENCES link_item(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT,
    official_name TEXT,
    mask TEXT,
    subtype TEXT,
    type TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_link_account_plaid_account_id ON link_account(plaid_account_id);
CREATE INDEX IF NOT EXISTS idx_link_account_item_id ON link_account(item_id);
CREATE INDEX IF NOT EXISTS idx_link_account_user_id ON link_account(user_id);

-- +goose Down
DROP INDEX IF EXISTS idx_link_account_plaid_account_id;
DROP INDEX IF EXISTS idx_link_account_item_id;
DROP INDEX IF EXISTS idx_link_account_user_id;
DROP TABLE IF EXISTS link_account; 