-- Link domain schema
CREATE TABLE IF NOT EXISTS link_item (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    access_token TEXT NOT NULL, -- encrypt at rest
    item_id TEXT NOT NULL,
    institution_id TEXT,
    institution_name TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_link_item_user_id ON link_item(user_id);
CREATE INDEX IF NOT EXISTS idx_link_item_item_id ON link_item(item_id);
CREATE INDEX IF NOT EXISTS idx_link_item_access_token ON link_item(access_token);

CREATE TABLE IF NOT EXISTS link_account (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_id TEXT NOT NULL UNIQUE, -- encrypt at rest
    item_id BIGINT NOT NULL REFERENCES link_item(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT,
    official_name TEXT,
    mask TEXT,
    subtype TEXT,
    type TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_link_account_account_id ON link_account(account_id);
CREATE INDEX IF NOT EXISTS idx_link_account_item_id ON link_account(item_id);
CREATE INDEX IF NOT EXISTS idx_link_account_user_id ON link_account(user_id); 